---
title: "01_load"
format:
  html:
    self-contained: TRUE
---

```{r}
#| message: false
library("tidyverse")
```

## Load data

Data will be fetched from hbiostat from vanderbilt department of biostatistics.

```{r}
raw_dir <- "../data/_raw/"
data_file <- "prostate.rda"
data_loc <- "https://hbiostat.org/data/repo/"

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir, recursive = TRUE)
}

if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file),
    mode = "wb")
}
load(file = str_c(raw_dir, data_file))
```

### Metadata

```{r}
data_dir <- "../data/"
meta_tsv_file <- "01_meta_dat_load.tsv"
if (!file.exists(str_c(data_dir, meta_tsv_file)) ) {
  prostate |>
    select(patno, stage, status, age, wt, pf, hx, sdate) |>
    write_tsv(file = str_c(data_dir, meta_tsv_file))
}
```

### Treatment data

```{r}
treatment_tsv_file <- "01_treatment_dat_load.tsv"
if (!file.exists(str_c(data_dir, treatment_tsv_file)) ) {
  prostate |>
  select(-stage, -status, -age, -wt, -pf, -hx, -sdate) |>
    write_tsv(file = str_c(data_dir, treatment_tsv_file))
}
```
